spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://localhost:5432/loan
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:script.sql

server:
  port: 8080
